# REUSE 設定：批次涵蓋無法掛 inline SPDX header 的 manifest / 設定 / 文件檔，
# 與不能動內容的 lint 測試 fixture（Tests/Lint/Sources/ 為故意違規的測試資產）。
# 已掛 header 的 .swift 原始碼不在此列；授權全文見 LICENSES/MIT.txt。
version = 1

[[annotations]]
path = [
	".config/mise.toml",
	".github/CODEOWNERS",
	".github/dependabot.yml",
	".github/workflows/swiftlint-version-check.yml",
	".github/workflows/test.yml",
	".gitignore",
	"Package.swift",
	"README.md",
	"Tests/Lint/Package.swift",
	"Tests/Lint/Project.swift",
	"Tests/Lint/Sources/Failing.swift",
	"Tests/Lint/Sources/Passing.swift",
	"Tests/Lint/Sources/Warning.swift",
	"Tools/FormatRuleCodegen/Package.swift",
	"docs/CODEOWNERS",
	"docs/SECURITY.md",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Unpxre (GitHub: UnpxreTW)"
SPDX-License-Identifier = "MIT"
