//
//  SwiftStyleFormatCore
//
//  Copyright © 2026 Unpxre (GitHub: UnpxreTW)
//  Licensed under the MIT License. See LICENSE for details.
//
//  SPDX-License-Identifier: MIT

//  GENERATED by Tools/FormatRuleCodegen — DO NOT EDIT BY HAND.
//  規則工廠（過渡期 migrated → on/off、其餘 → 舊式 Flag）。改規則簽名請改 FormatRule.swift 的
//  Storage enum、遷移狀態改 migratedRules 後重跑 codegen。

// swiftformat:disable all
// 原因：本檔為 codegen 機械產出、簽名逐一對應 Storage 的原始 case（含 organizeDeclarations
// 等 8~22 參數的多 option 規則）。格式規則對「生成檔的可讀性」沒指引意義——要改格式請改
// codegen 模板、不手改本檔。故整檔停用 SwiftFormat。

// swiftlint:disable file_length
// 原因：全量生成 147 規則的工廠、檔案逾千行遠超門檻；file_length 對生成檔無意義。

// swiftlint:disable line_length vertical_parameter_alignment
// 原因：生成的工廠簽名逐字對應原 case、可能破 120、多行參數不垂直對齊；這些格式類規則對生成檔
// 無指引意義。需停的其他 swiftlint 規則隨更複雜規則加進此 disable。

extension FormatRule {

	// MARK: acronyms

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func acronyms(rule: Flag, _ value: String = FormatRule.defaultAcronyms) -> FormatRule {
		.init(.acronyms(rule: rule, value))
	}

	// MARK: andOperator

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func andOperator(rule: Flag) -> FormatRule {
		.init(.andOperator(rule: rule))
	}

	// MARK: anyObjectProtocol

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func anyObjectProtocol(rule: Flag) -> FormatRule {
		.init(.anyObjectProtocol(rule: rule))
	}

	// MARK: applicationMain

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func applicationMain(rule: Flag) -> FormatRule {
		.init(.applicationMain(rule: rule))
	}

	// MARK: assertionFailures

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func assertionFailures(rule: Flag) -> FormatRule {
		.init(.assertionFailures(rule: rule))
	}

	// MARK: blankLineAfterImports

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func blankLineAfterImports(rule: Flag) -> FormatRule {
		.init(.blankLineAfterImports(rule: rule))
	}

	// MARK: blankLineAfterSwitchCase

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func blankLineAfterSwitchCase(rule: Flag, mode: BlankLineAfterSwitchCaseMode? = nil) -> FormatRule {
		.init(.blankLineAfterSwitchCase(rule: rule, mode: mode))
	}

	// MARK: blankLinesAfterGuardStatements

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func blankLinesAfterGuardStatements(rule: Flag, lineBetweenGuards: Toggle = .disable) -> FormatRule {
		.init(.blankLinesAfterGuardStatements(rule: rule, lineBetweenGuards: lineBetweenGuards))
	}

	// MARK: blankLinesAroundMark

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func blankLinesAroundMark(rule: Flag, lineAfterMarks: Toggle = .enable) -> FormatRule {
		.init(.blankLinesAroundMark(rule: rule, lineAfterMarks: lineAfterMarks))
	}

	// MARK: blankLinesAtEndOfScope

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func blankLinesAtEndOfScope(rule: Flag) -> FormatRule {
		.init(.blankLinesAtEndOfScope(rule: rule))
	}

	// MARK: blankLinesAtStartOfScope

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func blankLinesAtStartOfScope(rule: Flag) -> FormatRule {
		.init(.blankLinesAtStartOfScope(rule: rule))
	}

	// MARK: blankLinesBetweenChainedFunctions

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func blankLinesBetweenChainedFunctions(rule: Flag) -> FormatRule {
		.init(.blankLinesBetweenChainedFunctions(rule: rule))
	}

	// MARK: blankLinesBetweenImports

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func blankLinesBetweenImports(rule: Flag) -> FormatRule {
		.init(.blankLinesBetweenImports(rule: rule))
	}

	// MARK: blankLinesBetweenScopes

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func blankLinesBetweenScopes(rule: Flag) -> FormatRule {
		.init(.blankLinesBetweenScopes(rule: rule))
	}

	// MARK: blockComments

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func blockComments(rule: Flag) -> FormatRule {
		.init(.blockComments(rule: rule))
	}

	// MARK: braces

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func braces(rule: Flag, allman: Toggle = .disable) -> FormatRule {
		.init(.braces(rule: rule, allman: allman))
	}

	// MARK: conditionalAssignment

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func conditionalAssignment(rule: Flag, mode: ConditionalAssignmentMode = .always) -> FormatRule {
		.init(.conditionalAssignment(rule: rule, mode: mode))
	}

	// MARK: consecutiveBlankLines

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func consecutiveBlankLines(rule: Flag) -> FormatRule {
		.init(.consecutiveBlankLines(rule: rule))
	}

	// MARK: consecutiveSpaces

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func consecutiveSpaces(rule: Flag) -> FormatRule {
		.init(.consecutiveSpaces(rule: rule))
	}

	// MARK: consistentSwitchCaseSpacing

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func consistentSwitchCaseSpacing(rule: Flag) -> FormatRule {
		.init(.consistentSwitchCaseSpacing(rule: rule))
	}

	// MARK: docComments

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func docComments(rule: Flag, mode: DocCommentsMode = .beforeDeclarations) -> FormatRule {
		.init(.docComments(rule: rule, mode: mode))
	}

	// MARK: docCommentsBeforeModifiers

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func docCommentsBeforeModifiers(rule: Flag) -> FormatRule {
		.init(.docCommentsBeforeModifiers(rule: rule))
	}

	// MARK: duplicateImports

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func duplicateImports(rule: Flag) -> FormatRule {
		.init(.duplicateImports(rule: rule))
	}

	// MARK: elseOnSameLine

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func elseOnSameLine(rule: Flag, elsePosition: ElsePosition = .sameLine, guardElse: GuardElsePosition = .nextLine) -> FormatRule {
		.init(.elseOnSameLine(rule: rule, elsePosition: elsePosition, guardElse: guardElse))
	}

	// MARK: emptyBraces

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func emptyBraces(rule: Flag, mode: EmptyBracesSpacing = .noSpace) -> FormatRule {
		.init(.emptyBraces(rule: rule, mode: mode))
	}

	// MARK: emptyExtensions

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func emptyExtensions(rule: Flag) -> FormatRule {
		.init(.emptyExtensions(rule: rule))
	}

	// MARK: enumNamespaces

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func enumNamespaces(rule: Flag, mode: EnumNamespacesMode = .always) -> FormatRule {
		.init(.enumNamespaces(rule: rule, mode: mode))
	}

	// MARK: environmentEntry

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func environmentEntry(rule: Flag) -> FormatRule {
		.init(.environmentEntry(rule: rule))
	}

	// MARK: extensionAccessControl

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func extensionAccessControl(rule: Flag, mode: ExtensionACLPlacement = .onDeclarations) -> FormatRule {
		.init(.extensionAccessControl(rule: rule, mode: mode))
	}

	// MARK: fileHeader

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func fileHeader(rule: Flag, header: String, dateFormat: String, timeZone: String) -> FormatRule {
		.init(.fileHeader(rule: rule, header: header, dateFormat: dateFormat, timeZone: timeZone))
	}

	// MARK: fileMacro

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func fileMacro(rule: Flag, mode: FileMacro = .fileID) -> FormatRule {
		.init(.fileMacro(rule: rule, mode: mode))
	}

	// MARK: genericExtensions

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func genericExtensions(rule: Flag, genericTypes: String? = nil) -> FormatRule {
		.init(.genericExtensions(rule: rule, genericTypes: genericTypes))
	}

	// MARK: headerFileName

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func headerFileName(rule: Flag) -> FormatRule {
		.init(.headerFileName(rule: rule))
	}

	// MARK: hoistAwait

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func hoistAwait(rule: Flag, asyncCapturing: String? = nil) -> FormatRule {
		.init(.hoistAwait(rule: rule, asyncCapturing: asyncCapturing))
	}

	// MARK: hoistPatternLet

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func hoistPatternLet(rule: Flag, mode: PatternLet = .hoist) -> FormatRule {
		.init(.hoistPatternLet(rule: rule, mode: mode))
	}

	// MARK: hoistTry

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func hoistTry(rule: Flag, throwCapturing: String? = nil) -> FormatRule {
		.init(.hoistTry(rule: rule, throwCapturing: throwCapturing))
	}

	// MARK: indent

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func indent(rule: Flag, indent: Indentation = .tab, tabWidth: Int? = nil, smartTabs: Toggle = .enable, indentCase: Toggle = .disable, ifdef: IfdefIndent = .outdent, xcodeIndentation: Toggle = .disable, indentStrings: Toggle = .enable) -> FormatRule {
		.init(.indent(rule: rule, indent: indent, tabWidth: tabWidth, smartTabs: smartTabs, indentCase: indentCase, ifdef: ifdef, xcodeIndentation: xcodeIndentation, indentStrings: indentStrings))
	}

	// MARK: initCoderUnavailable

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func initCoderUnavailable(rule: Flag, initCoderNil: Toggle = .disable) -> FormatRule {
		.init(.initCoderUnavailable(rule: rule, initCoderNil: initCoderNil))
	}

	// MARK: isEmpty

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func isEmpty(rule: Flag) -> FormatRule {
		.init(.isEmpty(rule: rule))
	}

	// MARK: leadingDelimiters

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func leadingDelimiters(rule: Flag) -> FormatRule {
		.init(.leadingDelimiters(rule: rule))
	}

	// MARK: linebreakAtEndOfFile

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func linebreakAtEndOfFile(rule: Flag) -> FormatRule {
		.init(.linebreakAtEndOfFile(rule: rule))
	}

	// MARK: linebreaks

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func linebreaks(rule: Flag, mode: Linebreak = .lf) -> FormatRule {
		.init(.linebreaks(rule: rule, mode: mode))
	}

	// MARK: markTypes

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func markTypes(rule: Flag, markTypes: MarkMode = .always, typeMark: String? = nil, markExtensions: MarkMode = .always, extensionMark: String? = "MARK: - + %c", groupedExtension: String? = "MARK: - + %c") -> FormatRule {
		.init(.markTypes(rule: rule, markTypes: markTypes, typeMark: typeMark, markExtensions: markExtensions, extensionMark: extensionMark, groupedExtension: groupedExtension))
	}

	// MARK: modifierOrder

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func modifierOrder(rule: Flag, modifierOrder: String? = nil) -> FormatRule {
		.init(.modifierOrder(rule: rule, modifierOrder: modifierOrder))
	}

	// MARK: modifiersOnSameLine

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func modifiersOnSameLine(rule: Flag) -> FormatRule {
		.init(.modifiersOnSameLine(rule: rule))
	}

	// MARK: noExplicitOwnership

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func noExplicitOwnership(rule: Flag) -> FormatRule {
		.init(.noExplicitOwnership(rule: rule))
	}

	// MARK: noForceTryInTests

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func noForceTryInTests(rule: Flag) -> FormatRule {
		.init(.noForceTryInTests(rule: rule))
	}

	// MARK: noForceUnwrapInTests

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func noForceUnwrapInTests(rule: Flag) -> FormatRule {
		.init(.noForceUnwrapInTests(rule: rule))
	}

	// MARK: noGuardInTests

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func noGuardInTests(rule: Flag) -> FormatRule {
		.init(.noGuardInTests(rule: rule))
	}

	// MARK: numberFormatting

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func numberFormatting(rule: Flag, decimalGrouping: String? = "3,5", binaryGrouping: String? = "4,4", octalGrouping: String? = "4,4", hexGrouping: String? = "4,4", fractionGrouping: Toggle = .enable, exponentGrouping: Toggle = .disable, hexLiteralCase: LetterCase = .uppercase, exponentCase: LetterCase = .lowercase) -> FormatRule {
		.init(.numberFormatting(rule: rule, decimalGrouping: decimalGrouping, binaryGrouping: binaryGrouping, octalGrouping: octalGrouping, hexGrouping: hexGrouping, fractionGrouping: fractionGrouping, exponentGrouping: exponentGrouping, hexLiteralCase: hexLiteralCase, exponentCase: exponentCase))
	}

	// MARK: organizeDeclarations

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func organizeDeclarations(rule: Flag, organizationMode: DeclarationOrganizationMode = .visibility, visibilityOrder: [String]? = [
			"beforeMarks",
			"open",
			"public",
			"package",
			"instanceLifecycle",
			"internal",
			"fileprivate",
			"private"
		], typeOrder: [String]? = [
			"nestedType",
			"staticProperty",
			"staticPropertyWithBody",
			"staticMethod",
			"classPropertyWithBody",
			"classMethod",
			"swiftUIProperty",
			"overriddenProperty",
			"swiftUIPropertyWrapper",
			"instancePropertyWithBody",
			"instanceProperty",
			"overriddenMethod",
			"swiftUIMethod",
			"instanceMethod"
		], visibilityMarks: String? = "fileprivate:File Private", typeMarks: String? = nil, categoryMark: String? = nil, markCategories: Toggle = .enable, beforeMarks: [String]? = nil, lifecycle: [String]? = [
			"viewDidLoad",
			"viewWillAppear",
			"viewDidAppear",
			"viewWillDisappear",
			"viewDidDisappear",
			"viewWillLayoutSubviews",
			"viewDidLayoutSubviews",
			"setUp",
			"tearDown",
			"setUpWithError",
			"tearDownWithError"
		], organizeTypes: [String]? = nil, classThreshold: Int? = nil, structThreshold: Int? = nil, enumThreshold: Int? = nil, extensionThreshold: Int? = nil, markClassThreshold: Int? = 80, markStructThreshold: Int? = 80, markEnumThreshold: Int? = 80, markExtensionThreshold: Int? = 80, sortSwiftUIProperties: SwiftUIPropertiesSortMode = .firstAppearanceSort, typeBodyMarks: TypeBodyMarks = .remove, groupBlankLines: Toggle = .enable) -> FormatRule {
		.init(.organizeDeclarations(rule: rule, organizationMode: organizationMode, visibilityOrder: visibilityOrder, typeOrder: typeOrder, visibilityMarks: visibilityMarks, typeMarks: typeMarks, categoryMark: categoryMark, markCategories: markCategories, beforeMarks: beforeMarks, lifecycle: lifecycle, organizeTypes: organizeTypes, classThreshold: classThreshold, structThreshold: structThreshold, enumThreshold: enumThreshold, extensionThreshold: extensionThreshold, markClassThreshold: markClassThreshold, markStructThreshold: markStructThreshold, markEnumThreshold: markEnumThreshold, markExtensionThreshold: markExtensionThreshold, sortSwiftUIProperties: sortSwiftUIProperties, typeBodyMarks: typeBodyMarks, groupBlankLines: groupBlankLines))
	}

	// MARK: opaqueGenericParameters

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func opaqueGenericParameters(rule: Flag, someAny: Toggle = .enable) -> FormatRule {
		.init(.opaqueGenericParameters(rule: rule, someAny: someAny))
	}

	// MARK: preferCountWhere

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func preferCountWhere(rule: Flag) -> FormatRule {
		.init(.preferCountWhere(rule: rule))
	}

	// MARK: preferExplicitFalse

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func preferExplicitFalse(rule: Flag) -> FormatRule {
		.init(.preferExplicitFalse(rule: rule))
	}

	// MARK: preferFinalClasses

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func preferFinalClasses(rule: Flag) -> FormatRule {
		.init(.preferFinalClasses(rule: rule))
	}

	// MARK: preferForLoop

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func preferForLoop(rule: Flag, anonymousForEach: ForEachConversion = .ignore, singleLineForEach: ForEachConversion = .ignore) -> FormatRule {
		.init(.preferForLoop(rule: rule, anonymousForEach: anonymousForEach, singleLineForEach: singleLineForEach))
	}

	// MARK: preferKeyPath

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func preferKeyPath(rule: Flag) -> FormatRule {
		.init(.preferKeyPath(rule: rule))
	}

	// MARK: preferSwiftStringAPI

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func preferSwiftStringAPI(rule: Flag) -> FormatRule {
		.init(.preferSwiftStringAPI(rule: rule))
	}

	// MARK: preferSwiftTesting

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func preferSwiftTesting(rule: Flag, defaultTestSuiteAttributes: [String]? = nil, xctestSymbols: [String]? = nil) -> FormatRule {
		.init(.preferSwiftTesting(rule: rule, defaultTestSuiteAttributes: defaultTestSuiteAttributes, xctestSymbols: xctestSymbols))
	}

	// MARK: privateStateVariables

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func privateStateVariables(rule: Flag) -> FormatRule {
		.init(.privateStateVariables(rule: rule))
	}

	// MARK: propertyTypes

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func propertyTypes(rule: Flag, propertyTypes: PropertyTypes = .explicit, inferredTypes: InferredTypesMode = .always, preservedPropertyTypes: [String]? = nil) -> FormatRule {
		.init(.propertyTypes(rule: rule, propertyTypes: propertyTypes, inferredTypes: inferredTypes, preservedPropertyTypes: preservedPropertyTypes))
	}

	// MARK: redundantAsync

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantAsync(rule: Flag, redundantAsync: RedundantEffectMode = .testsOnly) -> FormatRule {
		.init(.redundantAsync(rule: rule, redundantAsync: redundantAsync))
	}

	// MARK: redundantBackticks

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantBackticks(rule: Flag) -> FormatRule {
		.init(.redundantBackticks(rule: rule))
	}

	// MARK: redundantBreak

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantBreak(rule: Flag) -> FormatRule {
		.init(.redundantBreak(rule: rule))
	}

	// MARK: redundantClosure

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantClosure(rule: Flag) -> FormatRule {
		.init(.redundantClosure(rule: rule))
	}

	// MARK: redundantEmptyView

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantEmptyView(rule: Flag) -> FormatRule {
		.init(.redundantEmptyView(rule: rule))
	}

	// MARK: redundantEquatable

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantEquatable(rule: Flag, equatableMacro: String? = nil) -> FormatRule {
		.init(.redundantEquatable(rule: rule, equatableMacro: equatableMacro))
	}

	// MARK: redundantExtensionACL

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantExtensionACL(rule: Flag) -> FormatRule {
		.init(.redundantExtensionACL(rule: rule))
	}

	// MARK: redundantFileprivate

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantFileprivate(rule: Flag) -> FormatRule {
		.init(.redundantFileprivate(rule: rule))
	}

	// MARK: redundantGet

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantGet(rule: Flag) -> FormatRule {
		.init(.redundantGet(rule: rule))
	}

	// MARK: redundantInit

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantInit(rule: Flag) -> FormatRule {
		.init(.redundantInit(rule: rule))
	}

	// MARK: redundantInternal

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantInternal(rule: Flag) -> FormatRule {
		.init(.redundantInternal(rule: rule))
	}

	// MARK: redundantLet

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantLet(rule: Flag) -> FormatRule {
		.init(.redundantLet(rule: rule))
	}

	// MARK: redundantLetError

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantLetError(rule: Flag) -> FormatRule {
		.init(.redundantLetError(rule: rule))
	}

	// MARK: redundantMemberwiseInit

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantMemberwiseInit(rule: Flag, mode: PreferSynthesizedInitMode = .never) -> FormatRule {
		.init(.redundantMemberwiseInit(rule: rule, mode: mode))
	}

	// MARK: redundantPublic

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantPublic(rule: Flag) -> FormatRule {
		.init(.redundantPublic(rule: rule))
	}

	// MARK: redundantSendable

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantSendable(rule: Flag) -> FormatRule {
		.init(.redundantSendable(rule: rule))
	}

	// MARK: redundantSwiftTestingSuite

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantSwiftTestingSuite(rule: Flag) -> FormatRule {
		.init(.redundantSwiftTestingSuite(rule: rule))
	}

	// MARK: redundantThrows

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantThrows(rule: Flag, redundantThrows: RedundantEffectMode = .testsOnly) -> FormatRule {
		.init(.redundantThrows(rule: rule, redundantThrows: redundantThrows))
	}

	// MARK: redundantVariable

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantVariable(rule: Flag) -> FormatRule {
		.init(.redundantVariable(rule: rule))
	}

	// MARK: redundantViewBuilder

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantViewBuilder(rule: Flag) -> FormatRule {
		.init(.redundantViewBuilder(rule: rule))
	}

	// MARK: redundantNilInit

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantNilInit(rule: Flag, mode: NilInitMode = .remove) -> FormatRule {
		.init(.redundantNilInit(rule: rule, mode: mode))
	}

	// MARK: redundantObjc

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantObjc(rule: Flag) -> FormatRule {
		.init(.redundantObjc(rule: rule))
	}

	// MARK: redundantOptionalBinding

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantOptionalBinding(rule: Flag) -> FormatRule {
		.init(.redundantOptionalBinding(rule: rule))
	}

	// MARK: redundantParens

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantParens(rule: Flag) -> FormatRule {
		.init(.redundantParens(rule: rule))
	}

	// MARK: redundantPattern

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantPattern(rule: Flag) -> FormatRule {
		.init(.redundantPattern(rule: rule))
	}

	// MARK: redundantRawValues

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantRawValues(rule: Flag) -> FormatRule {
		.init(.redundantRawValues(rule: rule))
	}

	// MARK: redundantReturn

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantReturn(rule: Flag) -> FormatRule {
		.init(.redundantReturn(rule: rule))
	}

	// MARK: redundantSelf

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantSelf(rule: Flag, mode: SelfMode = .initOnly, selfRequired: String? = nil) -> FormatRule {
		.init(.redundantSelf(rule: rule, mode: mode, selfRequired: selfRequired))
	}

	// MARK: redundantStaticSelf

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantStaticSelf(rule: Flag) -> FormatRule {
		.init(.redundantStaticSelf(rule: rule))
	}

	// MARK: redundantType

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantType(rule: Flag) -> FormatRule {
		.init(.redundantType(rule: rule))
	}

	// MARK: redundantTypedThrows

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantTypedThrows(rule: Flag) -> FormatRule {
		.init(.redundantTypedThrows(rule: rule))
	}

	// MARK: redundantVoidReturnType

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func redundantVoidReturnType(rule: Flag, closureVoid: ClosureVoidReturn = .remove) -> FormatRule {
		.init(.redundantVoidReturnType(rule: rule, closureVoid: closureVoid))
	}

	// MARK: semicolons

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func semicolons(rule: Flag, mode: SemicolonsMode = .never) -> FormatRule {
		.init(.semicolons(rule: rule, mode: mode))
	}

	// MARK: simplifyGenericConstraints

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func simplifyGenericConstraints(rule: Flag) -> FormatRule {
		.init(.simplifyGenericConstraints(rule: rule))
	}

	// MARK: singlePropertyPerLine

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func singlePropertyPerLine(rule: Flag) -> FormatRule {
		.init(.singlePropertyPerLine(rule: rule))
	}

	// MARK: sortDeclarations

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func sortDeclarations(rule: Flag) -> FormatRule {
		.init(.sortDeclarations(rule: rule))
	}

	// MARK: sortImports

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func sortImports(rule: Flag, mode: ImportGrouping = .testableFirst) -> FormatRule {
		.init(.sortImports(rule: rule, mode: mode))
	}

	// MARK: sortSwitchCases

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func sortSwitchCases(rule: Flag) -> FormatRule {
		.init(.sortSwitchCases(rule: rule))
	}

	// MARK: sortTypealiases

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func sortTypealiases(rule: Flag) -> FormatRule {
		.init(.sortTypealiases(rule: rule))
	}

	// MARK: spaceAroundBraces

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func spaceAroundBraces(rule: Flag) -> FormatRule {
		.init(.spaceAroundBraces(rule: rule))
	}

	// MARK: spaceAroundBrackets

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func spaceAroundBrackets(rule: Flag) -> FormatRule {
		.init(.spaceAroundBrackets(rule: rule))
	}

	// MARK: spaceAroundComments

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func spaceAroundComments(rule: Flag) -> FormatRule {
		.init(.spaceAroundComments(rule: rule))
	}

	// MARK: spaceAroundGenerics

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func spaceAroundGenerics(rule: Flag) -> FormatRule {
		.init(.spaceAroundGenerics(rule: rule))
	}

	// MARK: spaceAroundOperators

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func spaceAroundOperators(rule: Flag, operatorFunc: OperatorSpacing = .remove, ranges: OperatorSpacing = .insert, typeDelimiter: DelimiterSpacing = .spaceAfter, noSpaceOperators: [String]? = nil) -> FormatRule {
		.init(.spaceAroundOperators(rule: rule, operatorFunc: operatorFunc, ranges: ranges, typeDelimiter: typeDelimiter, noSpaceOperators: noSpaceOperators))
	}

	// MARK: spaceAroundParens

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func spaceAroundParens(rule: Flag) -> FormatRule {
		.init(.spaceAroundParens(rule: rule))
	}

	// MARK: spaceInsideBraces

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func spaceInsideBraces(rule: Flag) -> FormatRule {
		.init(.spaceInsideBraces(rule: rule))
	}

	// MARK: spaceInsideBrackets

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func spaceInsideBrackets(rule: Flag) -> FormatRule {
		.init(.spaceInsideBrackets(rule: rule))
	}

	// MARK: spaceInsideComments

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func spaceInsideComments(rule: Flag) -> FormatRule {
		.init(.spaceInsideComments(rule: rule))
	}

	// MARK: spaceInsideGenerics

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func spaceInsideGenerics(rule: Flag) -> FormatRule {
		.init(.spaceInsideGenerics(rule: rule))
	}

	// MARK: spaceInsideParens

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func spaceInsideParens(rule: Flag) -> FormatRule {
		.init(.spaceInsideParens(rule: rule))
	}

	// MARK: strongOutlets

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func strongOutlets(rule: Flag) -> FormatRule {
		.init(.strongOutlets(rule: rule))
	}

	// MARK: strongifiedSelf

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func strongifiedSelf(rule: Flag) -> FormatRule {
		.init(.strongifiedSelf(rule: rule))
	}

	// MARK: swiftTestingTestCaseNames

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func swiftTestingTestCaseNames(rule: Flag, testCaseNameFormat: SwiftTestingNameFormat = .rawIdentifiers, suiteNameFormat: SwiftTestingNameFormat = .preserve) -> FormatRule {
		.init(.swiftTestingTestCaseNames(rule: rule, testCaseNameFormat: testCaseNameFormat, suiteNameFormat: suiteNameFormat))
	}

	// MARK: testSuiteAccessControl

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func testSuiteAccessControl(rule: Flag, testCaseAccessControl: TestCaseAccessControl = .private) -> FormatRule {
		.init(.testSuiteAccessControl(rule: rule, testCaseAccessControl: testCaseAccessControl))
	}

	// MARK: todos

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func todos(rule: Flag) -> FormatRule {
		.init(.todos(rule: rule))
	}

	// MARK: trailingClosures

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func trailingClosures(rule: Flag, trailingClosures: [String]? = nil, neverTrailing: [String]? = nil) -> FormatRule {
		.init(.trailingClosures(rule: rule, trailingClosures: trailingClosures, neverTrailing: neverTrailing))
	}

	// MARK: trailingCommas

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func trailingCommas(rule: Flag, mode: TrailingCommas = .never) -> FormatRule {
		.init(.trailingCommas(rule: rule, mode: mode))
	}

	// MARK: trailingSpace

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func trailingSpace(rule: Flag, mode: TrimWhitespace = .always) -> FormatRule {
		.init(.trailingSpace(rule: rule, mode: mode))
	}

	// MARK: typeSugar

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func typeSugar(rule: Flag, mode: OptionalsMode = .preserveStructInits) -> FormatRule {
		.init(.typeSugar(rule: rule, mode: mode))
	}

	// MARK: unusedArguments

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func unusedArguments(rule: Flag, mode: ArgumentStrippingMode = .closureOnly) -> FormatRule {
		.init(.unusedArguments(rule: rule, mode: mode))
	}

	// MARK: unusedPrivateDeclarations

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func unusedPrivateDeclarations(rule: Flag, preserveDecls: String? = nil) -> FormatRule {
		.init(.unusedPrivateDeclarations(rule: rule, preserveDecls: preserveDecls))
	}

	// MARK: urlMacro

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func urlMacro(rule: Flag, urlMacro: String? = nil) -> FormatRule {
		.init(.urlMacro(rule: rule, urlMacro: urlMacro))
	}

	// MARK: validateTestCases

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func validateTestCases(rule: Flag) -> FormatRule {
		.init(.validateTestCases(rule: rule))
	}

	// MARK: void

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func void(rule: Flag, mode: VoidType = .void) -> FormatRule {
		.init(.void(rule: rule, mode: mode))
	}

	// MARK: wrap

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrap(rule: Flag, maxWidth: Int = 120, noWrapOperators: [String]? = nil, assetLiterals: AssetLiteralWidth = .actualWidth, wrapTernary: TernaryOperatorWrapMode = .default) -> FormatRule {
		.init(.wrap(rule: rule, maxWidth: maxWidth, noWrapOperators: noWrapOperators, assetLiterals: assetLiterals, wrapTernary: wrapTernary))
	}

	// MARK: wrapArguments

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapArguments(rule: Flag, wrapArguments: WrapMode = .preserve, wrapParameters: WrapMode = .beforeFirst, wrapCollections: WrapMode = .preserve, wrapConditions: WrapMode = .beforeFirst, wrapTypeAliases: WrapMode = .preserve, wrapEffects: WrapEffects = .preserve, wrapReturnType: WrapEffects = .preserve, closingParen: ParenPlacement = .balanced, callSiteParen: ParenPlacement = .balanced, allowPartialWrapping: Toggle = .enable) -> FormatRule {
		.init(.wrapArguments(rule: rule, wrapArguments: wrapArguments, wrapParameters: wrapParameters, wrapCollections: wrapCollections, wrapConditions: wrapConditions, wrapTypeAliases: wrapTypeAliases, wrapEffects: wrapEffects, wrapReturnType: wrapReturnType, closingParen: closingParen, callSiteParen: callSiteParen, allowPartialWrapping: allowPartialWrapping))
	}

	// MARK: wrapAttributes

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapAttributes(rule: Flag, funcAttributes: AttributeMode = .prevLine, typeAttributes: AttributeMode = .prevLine, storedVarAttributes: AttributeMode = .prevLine, computedVarAttributes: AttributeMode = .prevLine, complexAttributes: AttributeMode = .prevLine, nonComplexAttributes: [String]? = nil) -> FormatRule {
		.init(.wrapAttributes(rule: rule, funcAttributes: funcAttributes, typeAttributes: typeAttributes, storedVarAttributes: storedVarAttributes, computedVarAttributes: computedVarAttributes, complexAttributes: complexAttributes, nonComplexAttributes: nonComplexAttributes))
	}

	// MARK: wrapCaseBodies

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapCaseBodies(rule: Flag) -> FormatRule {
		.init(.wrapCaseBodies(rule: rule))
	}

	// MARK: wrapConditionalBodies

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapConditionalBodies(rule: Flag) -> FormatRule {
		.init(.wrapConditionalBodies(rule: rule))
	}

	// MARK: wrapEnumCases

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapEnumCases(rule: Flag, wrapEnumCases: WrapEnumCases = .always) -> FormatRule {
		.init(.wrapEnumCases(rule: rule, wrapEnumCases: wrapEnumCases))
	}

	// MARK: wrapFunctionBodies

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapFunctionBodies(rule: Flag) -> FormatRule {
		.init(.wrapFunctionBodies(rule: rule))
	}

	// MARK: wrapLoopBodies

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapLoopBodies(rule: Flag) -> FormatRule {
		.init(.wrapLoopBodies(rule: rule))
	}

	// MARK: wrapMultilineConditionalAssignment

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapMultilineConditionalAssignment(rule: Flag) -> FormatRule {
		.init(.wrapMultilineConditionalAssignment(rule: rule))
	}

	// MARK: wrapMultilineFunctionChains

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapMultilineFunctionChains(rule: Flag) -> FormatRule {
		.init(.wrapMultilineFunctionChains(rule: rule))
	}

	// MARK: wrapMultilineStatementBraces

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapMultilineStatementBraces(rule: Flag) -> FormatRule {
		.init(.wrapMultilineStatementBraces(rule: rule))
	}

	// MARK: wrapPropertyBodies

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapPropertyBodies(rule: Flag) -> FormatRule {
		.init(.wrapPropertyBodies(rule: rule))
	}

	// MARK: wrapSingleLineComments

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapSingleLineComments(rule: Flag) -> FormatRule {
		.init(.wrapSingleLineComments(rule: rule))
	}

	// MARK: wrapSwitchCases

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func wrapSwitchCases(rule: Flag) -> FormatRule {
		.init(.wrapSwitchCases(rule: rule))
	}

	// MARK: yodaConditions

	/// 啟用（`.enable`）或停用（`.disable`）——過渡相容工廠，待遷型別安全 `.on` / `.off`
	public static func yodaConditions(rule: Flag, mode: YodaMode = .always) -> FormatRule {
		.init(.yodaConditions(rule: rule, mode: mode))
	}

	// MARK: typeBlankLines

	/// 全域 option（無 rule Flag）：直接 passthrough，無 on/off 之分
	public static func typeBlankLines(mode: TypeBlankLines? = .preserve) -> FormatRule {
		.init(.typeBlankLines(mode: mode))
	}

	// MARK: wrapStringInterpolation

	/// 全域 option（無 rule Flag）：直接 passthrough，無 on/off 之分
	public static func wrapStringInterpolation(mode: StringInterpolationWrapMode? = .default) -> FormatRule {
		.init(.wrapStringInterpolation(mode: mode))
	}

	// MARK: sortedImports

	/// 改用 ``sortImports``（已棄用別名）
	@available(*, deprecated, renamed: "sortImports")
	public static func sortedImports(rule: Flag, mode: ImportGrouping = .testableFirst) -> FormatRule {
		.init(.sortedImports(rule: rule, mode: mode))
	}

	// MARK: sortedSwitchCases

	/// 改用 ``sortSwitchCases``（已棄用別名）
	@available(*, deprecated, renamed: "sortSwitchCases")
	public static func sortedSwitchCases(rule: Flag) -> FormatRule {
		.init(.sortedSwitchCases(rule: rule))
	}

	// MARK: specifiers

	/// 改用 ``modifierOrder``（已棄用別名）
	@available(*, deprecated, renamed: "modifierOrder")
	public static func specifiers(rule: Flag, modifierOrder: String? = nil) -> FormatRule {
		.init(.specifiers(rule: rule, modifierOrder: modifierOrder))
	}

	// MARK: throwingTests

	/// 改用 ``noForceTryInTests``（已棄用別名）
	@available(*, deprecated, renamed: "noForceTryInTests")
	public static func throwingTests(rule: Flag) -> FormatRule {
		.init(.throwingTests(rule: rule))
	}

	// MARK: redundantProperty

	/// 改用 ``redundantVariable``（已棄用別名）
	@available(*, deprecated, renamed: "redundantVariable")
	public static func redundantProperty(rule: Flag) -> FormatRule {
		.init(.redundantProperty(rule: rule))
	}
}

// swiftlint:enable line_length vertical_parameter_alignment
