//
//  SwiftStyleFormatCore
//
//  Copyright © 2026 Unpxre (GitHub: UnpxreTW)
//  Licensed under the MIT License. See LICENSE for details.
//
//  SPDX-License-Identifier: MIT

//  GENERATED by Tools/FormatRuleCodegen — DO NOT EDIT BY HAND.
//  型別安全 enable/disable/diagnostic overloads。改規則簽名請改 FormatRule.swift 後重跑 codegen。

// swiftformat:disable all
// 原因：本檔為 codegen 機械產出、簽名逐一對應 FormatRule 的原始 case（含 organizeDeclarations
// 等 8~22 參數的多 option 規則）。wrap / wrapArguments / indent 等格式規則對「生成檔的可讀性」
// 沒指引意義——要改格式請改 codegen 模板、不手改本檔。故整檔停用 SwiftFormat。

// swiftlint:disable line_length
// 原因：生成的 overload 簽名（規則名＋型別）逐字對應原 case、可能破 120；line_length 對生成檔
// 無指引意義。需停的其他 swiftlint 規則隨更複雜規則遷移時逐條加進此 disable。

extension FormatRule {

	// MARK: acronyms

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func acronyms(rule: EnableToken, _ value: String = FormatRule.defaultAcronyms) -> FormatRule {
		._acronyms(rule: .enable, value)
	}

	/// 停用（不可帶 option）
	public static func acronyms(rule: DisableToken) -> FormatRule {
		._acronyms(rule: .disable)
	}

	@available(*, unavailable, message: "rule 為 .disable 時不可帶 option（option 只在 .enable 有效）")
	public static func acronyms(rule: DisableToken, _ value: String = FormatRule.defaultAcronyms) -> FormatRule {
		fatalError("unavailable")
	}

	// MARK: blankLineAfterSwitchCase

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func blankLineAfterSwitchCase(rule: EnableToken, mode: BlankLineAfterSwitchCaseMode? = nil) -> FormatRule {
		._blankLineAfterSwitchCase(rule: .enable, mode: mode)
	}

	/// 停用（不可帶 option）
	public static func blankLineAfterSwitchCase(rule: DisableToken) -> FormatRule {
		._blankLineAfterSwitchCase(rule: .disable)
	}

	@available(*, unavailable, message: "rule 為 .disable 時不可帶 option（option 只在 .enable 有效）")
	public static func blankLineAfterSwitchCase(rule: DisableToken, mode: BlankLineAfterSwitchCaseMode? = nil) -> FormatRule {
		fatalError("unavailable")
	}
}

// swiftlint:enable line_length
