//
//  SwiftStyleFormatCore
//
//  Copyright © 2026 Unpxre (GitHub: UnpxreTW)
//  Licensed under the MIT License. See LICENSE for details.
//
//  SPDX-License-Identifier: MIT

//  GENERATED by Tools/FormatRuleCodegen — DO NOT EDIT BY HAND.
//  已遷規則的型別安全 .on/.off 工廠。改 Storage case 簽名 / 搬規則進 Storage 後重跑 codegen。

// swiftformat:disable all
// 原因：本檔為 codegen 機械產出、簽名逐一對應 Storage 的原始 case。格式規則對生成檔可讀性無指引意義。

// swiftlint:disable line_length
// 原因：生成的工廠簽名逐字對應原 case、行長 / 多行對齊對機械產出無指引意義。

extension FormatRule {

	// MARK: acronyms

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func acronyms(_ state: OnToken, _ value: String = FormatRule.defaultAcronyms) -> FormatRule {
		._storage(.acronyms(rule: .enable, value))
	}

	/// 停用（不可帶 option）
	public static func acronyms(_ state: OffToken) -> FormatRule {
		._storage(.acronyms(rule: .disable))
	}

	/// `.off` 誤帶 option 的編譯期診斷（命中即報錯、不會被呼叫）
	@available(*, unavailable, message: ".off 不可帶 option（option 只在 .on 有效）")
	public static func acronyms(_ state: OffToken, _ value: String = FormatRule.defaultAcronyms) -> FormatRule {
		fatalError("unavailable")
	}

	// MARK: blankLineAfterSwitchCase

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func blankLineAfterSwitchCase(_ state: OnToken, mode: BlankLineAfterSwitchCaseMode? = nil) -> FormatRule {
		._storage(.blankLineAfterSwitchCase(rule: .enable, mode: mode))
	}

	/// 停用（不可帶 option）
	public static func blankLineAfterSwitchCase(_ state: OffToken) -> FormatRule {
		._storage(.blankLineAfterSwitchCase(rule: .disable))
	}

	/// `.off` 誤帶 option 的編譯期診斷（命中即報錯、不會被呼叫）
	@available(*, unavailable, message: ".off 不可帶 option（option 只在 .on 有效）")
	public static func blankLineAfterSwitchCase(_ state: OffToken, mode: BlankLineAfterSwitchCaseMode? = nil) -> FormatRule {
		fatalError("unavailable")
	}

	// MARK: andOperator

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func andOperator(_ state: OnToken) -> FormatRule {
		._storage(.andOperator(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func andOperator(_ state: OffToken) -> FormatRule {
		._storage(.andOperator(rule: .disable))
	}

	// MARK: anyObjectProtocol

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func anyObjectProtocol(_ state: OnToken) -> FormatRule {
		._storage(.anyObjectProtocol(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func anyObjectProtocol(_ state: OffToken) -> FormatRule {
		._storage(.anyObjectProtocol(rule: .disable))
	}

	// MARK: applicationMain

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func applicationMain(_ state: OnToken) -> FormatRule {
		._storage(.applicationMain(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func applicationMain(_ state: OffToken) -> FormatRule {
		._storage(.applicationMain(rule: .disable))
	}

	// MARK: assertionFailures

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func assertionFailures(_ state: OnToken) -> FormatRule {
		._storage(.assertionFailures(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func assertionFailures(_ state: OffToken) -> FormatRule {
		._storage(.assertionFailures(rule: .disable))
	}

	// MARK: blankLineAfterImports

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func blankLineAfterImports(_ state: OnToken) -> FormatRule {
		._storage(.blankLineAfterImports(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func blankLineAfterImports(_ state: OffToken) -> FormatRule {
		._storage(.blankLineAfterImports(rule: .disable))
	}

	// MARK: preferContains

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func preferContains(_ state: OnToken) -> FormatRule {
		._storage(.preferContains(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func preferContains(_ state: OffToken) -> FormatRule {
		._storage(.preferContains(rule: .disable))
	}

	// MARK: preferFirstWhere

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func preferFirstWhere(_ state: OnToken) -> FormatRule {
		._storage(.preferFirstWhere(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func preferFirstWhere(_ state: OffToken) -> FormatRule {
		._storage(.preferFirstWhere(rule: .disable))
	}

	// MARK: preferFlatMap

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func preferFlatMap(_ state: OnToken) -> FormatRule {
		._storage(.preferFlatMap(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func preferFlatMap(_ state: OffToken) -> FormatRule {
		._storage(.preferFlatMap(rule: .disable))
	}

	// MARK: preferMinOverSorted

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func preferMinOverSorted(_ state: OnToken) -> FormatRule {
		._storage(.preferMinOverSorted(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func preferMinOverSorted(_ state: OffToken) -> FormatRule {
		._storage(.preferMinOverSorted(rule: .disable))
	}

	// MARK: redundantSwiftUIGroup

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func redundantSwiftUIGroup(_ state: OnToken) -> FormatRule {
		._storage(.redundantSwiftUIGroup(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func redundantSwiftUIGroup(_ state: OffToken) -> FormatRule {
		._storage(.redundantSwiftUIGroup(rule: .disable))
	}

	// MARK: blankLinesAfterGuardStatements

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func blankLinesAfterGuardStatements(_ state: OnToken, lineBetweenGuards: Toggle = .disable) -> FormatRule {
		._storage(.blankLinesAfterGuardStatements(rule: .enable, lineBetweenGuards: lineBetweenGuards))
	}

	/// 停用（不可帶 option）
	public static func blankLinesAfterGuardStatements(_ state: OffToken) -> FormatRule {
		._storage(.blankLinesAfterGuardStatements(rule: .disable))
	}

	/// `.off` 誤帶 option 的編譯期診斷（命中即報錯、不會被呼叫）
	@available(*, unavailable, message: ".off 不可帶 option（option 只在 .on 有效）")
	public static func blankLinesAfterGuardStatements(_ state: OffToken, lineBetweenGuards: Toggle = .disable) -> FormatRule {
		fatalError("unavailable")
	}

	// MARK: blankLinesAroundMark

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func blankLinesAroundMark(_ state: OnToken, lineAfterMarks: Toggle = .enable) -> FormatRule {
		._storage(.blankLinesAroundMark(rule: .enable, lineAfterMarks: lineAfterMarks))
	}

	/// 停用（不可帶 option）
	public static func blankLinesAroundMark(_ state: OffToken) -> FormatRule {
		._storage(.blankLinesAroundMark(rule: .disable))
	}

	/// `.off` 誤帶 option 的編譯期診斷（命中即報錯、不會被呼叫）
	@available(*, unavailable, message: ".off 不可帶 option（option 只在 .on 有效）")
	public static func blankLinesAroundMark(_ state: OffToken, lineAfterMarks: Toggle = .enable) -> FormatRule {
		fatalError("unavailable")
	}

	// MARK: blankLinesAtEndOfScope

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func blankLinesAtEndOfScope(_ state: OnToken) -> FormatRule {
		._storage(.blankLinesAtEndOfScope(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func blankLinesAtEndOfScope(_ state: OffToken) -> FormatRule {
		._storage(.blankLinesAtEndOfScope(rule: .disable))
	}

	// MARK: blankLinesAtStartOfScope

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func blankLinesAtStartOfScope(_ state: OnToken) -> FormatRule {
		._storage(.blankLinesAtStartOfScope(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func blankLinesAtStartOfScope(_ state: OffToken) -> FormatRule {
		._storage(.blankLinesAtStartOfScope(rule: .disable))
	}

	// MARK: blankLinesBetweenChainedFunctions

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func blankLinesBetweenChainedFunctions(_ state: OnToken) -> FormatRule {
		._storage(.blankLinesBetweenChainedFunctions(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func blankLinesBetweenChainedFunctions(_ state: OffToken) -> FormatRule {
		._storage(.blankLinesBetweenChainedFunctions(rule: .disable))
	}

	// MARK: blankLinesBetweenImports

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func blankLinesBetweenImports(_ state: OnToken) -> FormatRule {
		._storage(.blankLinesBetweenImports(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func blankLinesBetweenImports(_ state: OffToken) -> FormatRule {
		._storage(.blankLinesBetweenImports(rule: .disable))
	}

	// MARK: blankLinesBetweenScopes

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func blankLinesBetweenScopes(_ state: OnToken) -> FormatRule {
		._storage(.blankLinesBetweenScopes(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func blankLinesBetweenScopes(_ state: OffToken) -> FormatRule {
		._storage(.blankLinesBetweenScopes(rule: .disable))
	}

	// MARK: blockComments

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func blockComments(_ state: OnToken) -> FormatRule {
		._storage(.blockComments(rule: .enable))
	}

	/// 停用（不可帶 option）
	public static func blockComments(_ state: OffToken) -> FormatRule {
		._storage(.blockComments(rule: .disable))
	}

	// MARK: braces

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func braces(_ state: OnToken, allman: Toggle = .disable) -> FormatRule {
		._storage(.braces(rule: .enable, allman: allman))
	}

	/// 停用（不可帶 option）
	public static func braces(_ state: OffToken) -> FormatRule {
		._storage(.braces(rule: .disable))
	}

	/// `.off` 誤帶 option 的編譯期診斷（命中即報錯、不會被呼叫）
	@available(*, unavailable, message: ".off 不可帶 option（option 只在 .on 有效）")
	public static func braces(_ state: OffToken, allman: Toggle = .disable) -> FormatRule {
		fatalError("unavailable")
	}

	// MARK: conditionalAssignment

	/// 啟用 + 帶 option（option 預設＝原 SSK 簽名預設）
	public static func conditionalAssignment(_ state: OnToken, mode: ConditionalAssignmentMode = .always) -> FormatRule {
		._storage(.conditionalAssignment(rule: .enable, mode: mode))
	}

	/// 停用（不可帶 option）
	public static func conditionalAssignment(_ state: OffToken) -> FormatRule {
		._storage(.conditionalAssignment(rule: .disable))
	}

	/// `.off` 誤帶 option 的編譯期診斷（命中即報錯、不會被呼叫）
	@available(*, unavailable, message: ".off 不可帶 option（option 只在 .on 有效）")
	public static func conditionalAssignment(_ state: OffToken, mode: ConditionalAssignmentMode = .always) -> FormatRule {
		fatalError("unavailable")
	}
}

// swiftlint:enable line_length
